server:
  mode: gateway # 服务模式 manage(管理服务器[单])、webserver(接口服务器[多])、gateway(网关服务器[多])、chat(聊天服务器[多])、match(匹配服务器[单])、game(游戏服务器[多])
  url: http://localhost # 项目地址/域名/项目访问地址/上传资源访问地址
  host: 0.0.0.0 # 服务监听地址
  port: 9312 # 服务监听端口
  grpc_port: 9313 # grpc服务监听端口
  ip: 192.168.1.99 # 服务器ip，内网或者公网ip
  debug: false # debug模式
  env: local # 环境 local production
  log_access: ./storage/logs/go_access.log # 访问日志保存地址
  log_error: ./storage/logs/go_error.log # 错误日志保存地址
  template: false # 加载模板 false 的时候 部署可以不需要resources目录
  manage_ws: ws://192.168.1.99:6001/ws/manage # 管理服务器ws地址，当服务模式不是manage和web时需要提供这个地址，这个地址是manage服务器的地址，只能运行一个manage
  manage_rpc: 192.168.1.99:6002 # 管理服务器grpc地址

mysql:
  host: 127.0.0.1
  port: 3306
  database: db_test # 数据库名
  username: root
  password: 123456
  prefix: m_
  log: false        # 开启sql日志，打印sql执行日志到控制台
  save_log: false   # 保存sql日志到文本，需要先开启sql日志
  log_path: ./storage/logs/sql.log # sql 日志保存地址，需要先开启 保存sql日志到文本
  pool: 3 # 连接池数量
  ping: 60 # 心跳时间

redis:
  host: 127.0.0.1
  port: 6379
  password:
  prefix: m_ # redis前缀
  pool: 3 # 连接池数量
  ping: 60 # 心跳时间
  db: 0 # 使用几号数据库

rsa:
  public_key: ./config/rsa_public.key
  private_key: ./config/rsa_private.key

other:
  public_dir: D:/phpstudy_pro/WWW/public/upload/ # 其中 D:/phpstudy_pro/WWW 是nginx的静态资源目录
  public_prefix: /public/upload/
  token_key: DcV8JaEiCBefsTYI2
  aes_key:  0tgiAkjhvKrXbrG5 # AES 16位字符密码

push:
  use: false # 开启异常推送(env是production时可用)
  mode: bark # 推送方式
  bark_url: https://api.day.app/c8wXoYgSu3RmivLjE9ra7/ # bark推送地址
  ding_talk_url: https://oapi.dingtalk.com/robot/send?access_token=473af72d23c9b8b9cdb1d3b5af8dc1f2d2a0c15c15107dbb7b87dd141d6d86b0 # 钉钉推送地址
  wechat_url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=61fcdc63-fe8c-4492-8d73-089bc65d4672 # 企业微信推送地址

qiniuyun:
  bucket: fanrw # 空间名称
  access_key: N-ocIxALExq0PhTZzhCCkzkpLSt7GSGjta2oskCk #七牛云AK
  secret_key: BFwd0-3b8yPzdgmNaesQryTJVL0CpwtXyZoJJ-Ow # 七牛云SK

email:
  name: Break # 发件人名称
  user: buxsren@163.com # 发件人邮箱
  pass: QLRMPISFCUAYIENQ # 发件人密码
  host: smtp.163.com # 邮箱服务器
  port: 465 # 邮箱端口

alipay: # 支付宝网页&移动应用支付配置
  appid: 20220122224500 # AppID
  private_key: ./config/alipay.key # 应用私钥路径，后缀也可以是txt，反正是文本就行
  notify_url: https://www.xxx.com/xxxx # 回调地址